config/routes.rb
Rails.application.routes.draw do
  
  get 'sports/index'
    resources :highlights do
      resources :comments
    end
    
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  
    resources :sessions
    resources :users
    
  root 'sports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :highlight
end

app/models/highlight.rb
class Highlight < ApplicationRecord
    has_many :users
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    belongs_to :highlight
    
    attr_accessor :email, :password, :password_confirmation
  
    validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
  
    def authorize
        redirect_to login_url, alert: "Please Sign In for access." if current_user.nil?
    end
  
  
    private
        def current_user
            @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end
        helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authorize, only: [:edit, :update, :destroy]
    
    def create
        @highlight = Highlight.find(params[:highlight_id])
        @comment = @highlight.comments.create(comment_params)
        redirect_to highlight_path(@highlight)
    end
    
    def destroy
        @highlight = Highlight.find(params[:highlight_id])
        @comment = @highlight.comments.find(params[:id])
        @comment.destroy
        redirect_to highlight_path(@highlight)
    end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @highlight, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:clip, :title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Welcome Back!"
    else
      flash.now.alert = "Email or Password is invalid."
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    
    def new
        @user = User.new
    end
  
    def create
            @user = User.new
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_url, notice: "Thank you for signing up!"
        else
            render "new"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %></strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.highlight, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @highlight, @highlight.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/highlights/_form.html.erb
<%= form_with(model: highlight, local: true) do |form| %>
  <% if highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="login-page">
    <div class="form">
      <form class="register-form">
        <%= form.label :title %>
          <%= form.text_field :title, id: :highlight_title %>
        <%= form.label :clip %>
          <%= form.text_field :clip, id: :highlight_clip %>
        <%= form.label :description %>
          <%= form.text_area :description, id: :highlight_description %>
        <button><%= form.submit %></button>
      </form>
        <%= link_to 'Back', highlights_path %>
    </div>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing Highlight</h1>

<%= render 'form', highlight: @highlight %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Content section --> 
<div class="showoff">
<% @highlights.each do |highlight| %>

    <div class="vid-container">
      <div class="title">
        <h5><%= highlight.title %></h5>
      </div>
      <div class="vid-preview">
        <video width="360">
          <source src="<%= highlight.clip %>" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
      </div>
      <div class="vid-description">
        <p><%= highlight.description %></p>
      </div>
        <div class="list">
          <div class="show">
            <button><%= link_to 'Show', highlight %></button>
          </div>
          <div class="edit">
            <button><%= link_to 'Edit', edit_highlight_path(highlight) %></button>
          </div>
          <div class="destroy">
            <button><%= link_to 'Delete', highlight, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          </div>
        </div>
    </div>
<% end %>
</div>

<!-- end content section -->

app/views/highlights/new.html.erb
<%= render 'form', highlight: @highlight %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<div class="showcase">
<div class="vid-showcase">
<div class="header">
<p>
  <h5><strong><%= @highlight.title %></strong></h5>
</p>
</div>

<p class="video-player">
  <link href="https://vjs.zencdn.net/5.10.4/video-js.css" rel="stylesheet">
  <div>
    <video id="my-video" class="video-js" controls preload="auto" width="1080" height="480" data-setup='{"playbackRates": [0.25, 0.5, 1, 1.5, 2] }'>
      <source src="<%= @highlight.clip %>" type='video/mp4'>
        <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>
  </div>

  <script src="https://vjs.zencdn.net/5.10.4/video.js"></script>
</p>
<p>
  <strong>Description:</strong>
  <%= @highlight.description %>
</p>
</div>

<div class="comment-container">
    <div class="add-comment">
        <h2>Add a comment:</h2>
        <%= render 'comments/form' %>
    </div>
    <div class="comments">
        <h2>Comments</h2>
        <%= render @highlight.comments %>
    </div>
</div>
</div>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', highlights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "TimeOut Media" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div id="container">
                        <!-- nav section -->
    <nav class="main-nav">
      <ul>
          <li><%= link_to 'Watch', highlights_path %></li>
          <li><%= link_to 'New Highlight', new_highlight_path %></li>
        <% if current_user %>
          <li>Logged in as <%= current_user.email %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>


                    <!-- end nav -->
    <%= yield %>
    
                    <!-- footer section -->
    
    <div id="engadget-footer-social-container">
        <footer id="engadget-footer-social">
            <div class="footer-left">
                <div class="newsletter">
                    <h6>Sign up for our newsletter</h6>
                        <div class="input-group">
                            <input class="input-group-field" type="email" placeholder="Email address">
                            <div class="input-group-button">
                            <input type="submit" class="button" value="Submit">
                            </div>
                        </div>
                </div>
            </div>
            <div class="footer-right">
                <h6>Follow us</h6>
                    <i class="fa fa-facebook-square fa-3x" aria-hidden="true"></i>
                    <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
                    <i class="fa fa-google-plus-square fa-3x" aria-hidden="true"></i>
                    <i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i>
            </div>
        </footer>
    </div>
    <div id="engadget-footer-contact-details-container">
        <footer id="engadget-footer-contact-details">
            <div class="footer-left">
                <div class="contact-details">
                    <ul>
                        <li><img class="thumbnail" src="https://s3.amazonaws.com/stevenspics/time+out+logo.png" width="60" height="90"></li>
                        <li><i class="fa fa-phone fa-lg" aria-hidden="true"></i> 01234 567890</li>
                        <li><a data-toggle="animatedModal10"><i class="fa fa-envelope-o" aria-hidden="true"></i> Contact us</a></li>
                        <li><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i> Street, City, County, Country</li>
                    </ul>
                </div>
            </div>
            <div class="footer-right">
                <ul class="menu align-right">
                    <li><a href="#">One</a></li>
                    <li><a href="#">Two</a></li>
                    <li><a href="#">Three</a></li>
                    <li><a href="#">Four</a></li>
                </ul>
            </div>
        </footer>
    </div>

                    <!-- end footer -->
</div>

  </body>
</html>

app/views/sports/index.html.erb
<div class="container">

                    
                    <!-- content section -->
    <div class="hero-section">
        <div class="hero-section-text">
            <h1></h1>
            <h5></h5>
        </div>
    </div>


                    <!-- end content -->
                    
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  
<div class="login-page">
  <div class="form">
    <form class="register-form">
      <%= f.label :email %><br />
        <%= f.text_field :email %>
      <%= f.label :password %><br />
        <%= f.password_field :password %>
      <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      <button><%= f.submit "Sign Up" %></button>
      <p class="message">Already registered?<%= link_to "Log In", login_path %></p>
    </form>
  </div>
</div>

<% end %>